project:
  type: website

website:
  title: "Othmane Elouardi"
  site-url: https://othmane-elouardi.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


